# File: netlify.toml

[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  [functions.node_bundler_options]
    external = ["node-fetch"] # not strictly needed for v18+, but good practice